// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///

namespace SquareConstants
{
public static class GPGSIds
{
        public const string leaderboard_top_impossible_players = "CgkIg-aMutYCEAIQEQ"; // <GPGSID>
        public const string achievement_500_points_keep_going = "CgkIg-aMutYCEAIQBA"; // <GPGSID>
        public const string achievement_impossible_100_points = "CgkIg-aMutYCEAIQCQ"; // <GPGSID>
        public const string achievement_impossible_300_points = "CgkIg-aMutYCEAIQDg"; // <GPGSID>
        public const string achievement_the_longest_journey_starts_with_a_single_step = "CgkIg-aMutYCEAIQAw"; // <GPGSID>
        public const string achievement_impossible_500_points = "CgkIg-aMutYCEAIQDA"; // <GPGSID>
        public const string achievement_nobody_really_came_that_far = "CgkIg-aMutYCEAIQBw"; // <GPGSID>
        public const string achievement_impossible_you_beat_the_creator_high_score = "CgkIg-aMutYCEAIQCg"; // <GPGSID>
        public const string achievement_1000_points = "CgkIg-aMutYCEAIQBQ"; // <GPGSID>
        public const string achievement_3000_points = "CgkIg-aMutYCEAIQBg"; // <GPGSID>
        public const string achievement_you_should_stop_now = "CgkIg-aMutYCEAIQCw"; // <GPGSID>
        public const string achievement_bot = "CgkIg-aMutYCEAIQCA"; // <GPGSID>
        public const string leaderboard_top_players = "CgkIg-aMutYCEAIQEA"; // <GPGSID>

}
}
